apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: airflow-config 
  namespace: "airflow"    
data: 
  executor: "KubernetesExecutor"
  sql_alchemy_conn: "postgresql://airflow_user:airflow_pass@postgres:5432/airflow_db"   
  multi-namespace-mode: "off"